defaults: &defaults
  aws_credentials:
    key: AKIAI5YJW26F3RO3COMQ
    secret: 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
  swf:
    domain: protrada
    retry: 3

production:
  <<: *defaults

staging:
  <<: *defaults
  aws_credentials:
    key: AKIAIAHWGHUBSRYOMN3Q
    secret: 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

development:
  <<: *defaults
  aws_credentials:
    key: AKIAJMBAHTKRQHXW3F6Q
    secret: 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